[project]
name = "imap"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "coverage>=7.6.9",
    "pytest>=8.3.4",
]

[dependency-groups]
dev = [
    "ruff>=0.8.4",
]
